export enum RoutePath {
  Home = '/',
  Login = '/userlogin',
  LoginNew = '/newuserlogin',
  PasswordCheck = '/passwordcheck',
  Register = '/usersignup',
  Marketplace = '/marketplace',
  Shop = '/shop',
  Userprofile = '/userprofile',
  Adminpage = '/adminpage',
  Dashboard = '/dashboard',
  Chat = '/chat',
  Hashiras = '/hashiras',
  Demons = '/demons',
  Characters = '/characters/tanjiro',
  AdminUsers = '/admin/users',
  AdminMissions = '/admin/missions',
  Missions = '/missions',
  Upload = '/upload',
  Debug = '/debug',
  DashboardDemo = '/dashboard-demo'
}
